### ISSUE TITLE
Allow Html Unescaped Output

### ISSUE THREAD

**Issue by micahasmith** [twitter/hogan.js#14]
Perhaps create a tag that means "allow html unescaped output", similar to jade? 

http://stackoverflow.com/questions/6926247/nodejs-jade-escape-markup

**Comment by wardhanster** [comment]
I Can't get HTML escape to work with changed delimiters. Any help in the direction ?

**Comment by neustroev** [comment]
@wardhanster @bentedder @denisrobert 
I know, this is quite old, but still.

[Mustache specs](https://mustache.github.io/mustache.5.html) allows to use `&` character after the delimiter. It works the same way as triple brace, but can be used with other delimiters as well.

From the spec:
> You can also use & to unescape a variable: {{& name}}. This may be useful when changing delimiters (see "Set Delimiter" below).

See working example with changed delimiters on RequireBin: 

[![view on requirebin](http://requirebin.com/badge.png)](http://requirebin.com/?gist=4ebd6f817e5a4b3cb0d24b95ee3dd0b8)

**Comment by oncode** [comment]
@denisrobert @bentedder @wardhanster 
I got it to work with using: `[[{variable}]]`
