### ISSUE TITLE
Standardize versioning and tags for Bower consumption

### ISSUE THREAD

**Issue by jjt** [twitter/hogan.js#167]
It seems weird to `$ bower install hogan#x.x.x` and then reference `bower_components/hogan/web/builds/x.x.x/hogan-x.x.x.js` in my markup. Most other Bower components are built so that the component version matches the tag. Not many have the versioning information in the path either, nor do they have old built versions included.

Let's say I wanted to install Hogan v3.0.0 (once #164 is merged). I'd expect to `$ bower install hogan#3.0.0` and reference `bower_components/hogan/dist/hogan.js` in my markup.

Also related, `/lib/hogan.js` states "This file is for use with Node.js. See dist/ for browser files".

**Comment by sayrer** [comment]
I'm going to close this, because I'm not sure anyone is still using Bower on new stuff. If I'm wrong, feel free to reopen or refile.
