### ISSUE TITLE
Use a more exhaustive encoder

### ISSUE THREAD

**Issue by tandrewnichols** [twitter/hogan.js#193]
We've had trouble with some unusually utf8 characters causing parse failures. Would you consider using something like [he](https://github.com/mathiasbynens/he) to encode strings?

**Comment by NatoBoram** [comment]
Is it normal that Hulk will eat my `Catégorie` in UTF-8 and spill out a `Cat├®gorie` in `UCS-2 LE BOM` or `UTF-16` or whatever and my computer can't read it?
