### ISSUE TITLE
Can't get lambdas to work

### ISSUE THREAD

**Issue by prashaantt** [twitter/hogan.js#199]
I [recently commented](https://github.com/twitter/hogan.js/issues/75#issuecomment-48222940) on #75 but realised it was closed while this one deserves a current issue of its own.

I just tested with the last v1 release (1.0.5) that I'm able to define a function like

``` javascript
var foo = function () {
  return function(text, render) {
    return bar(render(text));
  }
}
```

which I can then use with a template like `{{#foo}}{{baz}}{{/foo}}`. This works delightfully and solves all my templating problems.

I'm unable to get this behaviour working v2 onwards: I see the ugly `Uncaught ReferenceError: render is not defined` for the exact same code. Did something break along the way for it to be thus or am I missing something?

**Comment by MeTaNoV** [comment]
This differs then from the Mustache definition that could be find there:
http://mustache.github.io/mustache.5.html where you get both the text as template and the render function ready to be used. This was practical because you are force to reintroduce now a dependency on Hogan where your implementation needs the rendering...

**Comment by Jerskouille** [comment]
:+1: On @MeTaNoV comment.

http://twitter.github.io/hogan.js/ clearly states that everything should be handled the same way than in the mustache spec, and this clearly isn't the case.

Here is somewhat of a fix :
```js
  var renderer = function (self) {
    return function (text) {
      return Hogan.compile(text).render(self);
    };
  };
  var createLambda = function (lambda) {
    return function () {
      return function (text) {
        return lambda.call(this, text, renderer(this));
      };
    };
  };
```

And then I create my lambdas like this :

```js
createLambda(function(text, render) {
    return bar(render(text));
});
```

**Comment by MichielDeMey** [comment]
Thanks guys, I had the same issue.
I guess I expected Hogan to work as described in the Mustache(5) syntax, with an injected `render` function.
