### ISSUE TITLE
Is Hogan still alive ?

### ISSUE THREAD

**Issue by ram-you** [twitter/hogan.js#213]
Hi,
It is a long time we did not have new version. Is Hogan still alive?
I migrated all my projects from Handlebars and now I am afraid having to return back to it.

**Comment by sayrer** [comment]
Hey, do you have a specific issue? Hogan seems to mostly work.

**Comment by ram-you** [comment]
Hi, Hogan is awesome and have no issues. 
It's just to know if we can rely on it for the future.
Thank you.

**Comment by sayrer** [comment]
Well, it'll be supported, but there are no new features planned. If the Mustache spec is ever updated, it'll track that, assuming the changes are sane.

**Comment by ram-you** [comment]
:+1:

**Comment by gopalakrishnan-subramani** [comment]
Thank you, we started to use hogan js now on our mobile and web app.
