### ISSUE TITLE
3.0.2 CDN version should be created and docs be updated

### ISSUE THREAD

**Issue by powtac** [twitter/hogan.js#224]
Since 3.0.2 is the latest release according to https://github.com/twitter/hogan.js/releases the docs on http://twitter.github.io/hogan.js/ should refer to this release rather than 3.0.1 and the related [CDN version](http://twitter.github.com/hogan.js/builds/3.0.2/hogan-3.0.2.js) should be created.

**Comment by sayrer** [comment]
Going to duplicate this to #200.
