### ISSUE TITLE
NPM "official" hogan package => @bmullan91

### ISSUE THREAD

**Issue by mysegfault** [twitter/hogan.js#228]
Hi!

When you do `npm install hogan` it will download [the bmullan91 repository](https://github.com/bmullan91/hogan.git) and not the [official GIT repository](https://github.com/twitter/hogan.js.git). First consequence is that it's not clear for the developer, also the "hulk" binary does not appear in the ./node_modules/.bin folder.

Why not use the official GIT repository?
`npm install https://github.com/twitter/hogan.js.git` works great.

__Note__: if the reason why is because if this: 
`var hogan = require('hogan.js');`
instead of:
`var hogan = require('hogan');`

you should specify the
`
"bin": {
    "hulk": "./node_modules/hogan.js/bin/hulk"
}
`
in the bmullan91/hogan.git repository.

Thanks!

**Comment by davidosomething** [comment]
the package is `hogan.js`
`npm install hogan.js`

**Comment by mysegfault** [comment]
You are right. It's all fine then.
