### ISSUE TITLE
Documents should mention {{name.thing}} capability.

### ISSUE THREAD

**Issue by jimstudt** [twitter/hogan.js#230]
I don't see {{name.thing}} expansion on the mustache 5 man page or on the documentation presented here. I only stumbled upon it in the source while pondering how to add such a feature.

**Comment by sayrer** [comment]
This is covered in the mustache spec under "dotted names" https://github.com/mustache/spec/blob/44b04cbff0310ac672edafedfc77e1bcc0dd5e15/specs/sections.yml#L203
