### ISSUE TITLE
No documentation on $ tag

### ISSUE THREAD

**Issue by timgent** [twitter/hogan.js#232]
There is no documentation on the $ operator (at least not that I could find...).

A PR with an example is here:
mustache/spec#75

I raised an issue on mustache but seems it isn't yet an official feature, so I'm assuming it has been implemented in hogan itself, as the PR above mentioned.
https://github.com/mustache/mustache/issues/213#issuecomment-157014215

One particular thing that I am struggling with is if there is a way to have conditional logic for when one of the expected items to inherit isn't present.
e.g. If it is present do X, if not do Y, much like you would with normal objects.

**Comment by sayrer** [comment]
Closed in favor of #272.
