### ISSUE TITLE
How to embed json variables with in a script tag as a variable 

### ISSUE THREAD

**Issue by sijo-vijayan** [twitter/hogan.js#240]
I would like to embed http post variable into a javascript local variable in the .hjs template file.
I have done this like given below.

In the route handler

	app.post('/thankyou', function(req, res, next) {
		res.render('index',{ req: JSON.stringify(req.body) });
	});

In the index.hjs file

	<script>
	var postvar = {{req}}
	</script>

But json value printing in the final html like the following

	<script>
	var postvar = {&quot;username&quot;:&quot;sijo@example.com&quot;}
	</script>

Expected output is given below

	<script>
	var postvar = {'username':'sijo@example.com'}
	</script>

Please give me a solution.

**Comment by ex1st** [comment]
`
<script>
var postvar = {{{req}}}
</script>
`

**Comment by sijo-vijayan** [comment]
Now it working fine, I can't find this triple curly brackets anywhere on its readme file.
Where i can find the reference of this triple brackets ?

Thanks for your help.

**Comment by ex1st** [comment]
http://mustache.github.io/mustache.5.html

> All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.

**Comment by charliejlryan** [comment]
Hogan uses Mustache - {{{var}}} is the syntax for outputting unescaped HTML, and can be found on the Mustache GitHub as referenced by the Hogan readme https://mustache.github.io/mustache.5.html

**Comment by sijo-vijayan** [comment]
Thanks for you help @ex1st @charliejlryan
