### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by rtfpessoa** [twitter/hogan.js#248]
I was looking around and I could not find any answer to the question.

Is this project still being maintained? Can some one help me?

**Comment by herbertpimentel** [comment]
+1

**Comment by GregoryPotdevin** [comment]
I was wondering the same thing. Started using it for a project but am currently thinking of switching to Mustache.js.

**Comment by rtfpessoa** [comment]
Mustache.js is not an option for me because of the absence of pre-compilation.

**Comment by mikkotikkanen** [comment]
+1

**Comment by mschwartz** [comment]
+1

No changes since 2015.

**Comment by haikyuu** [comment]
Is it because it's stable or abandoned?

**Comment by sayrer** [comment]
Closed in favor of #272.
