### ISSUE TITLE
is twitter still using this on production?

### ISSUE THREAD

**Issue by genediazjr** [twitter/hogan.js#252]
If not, what are they using now?

**Comment by mschwartz** [comment]
Echo, echo, echo, echo...

**Comment by puppetmaster3** [comment]
?

**Comment by evoWeb** [comment]
Bump

**Comment by mschwartz** [comment]
Echo, echo, echo, echo...

**Comment by sayrer** [comment]
The main Twitter website is done in React now, so it's probably not used there. Don't know if they use it anywhere else.
