### ISSUE TITLE
Is Hogan dead or done? You owe it to the community to say one way or the other.

### ISSUE THREAD

**Issue by vassudanagunta** [twitter/hogan.js#271]
There has been no significant change for 6 years. But how is a person to know whether that is because the project is **done** (mature, complete, needing no more work) or **dead** (abandoned, whether because the authors got tired of it or because it lost out to the competition, or...).

The responsible/kind thing to do would be to update the README with some kind of statement. For example, see [Moment.js Project Status](https://momentjs.com/docs/#/-project-status/), and the [HackerNews discussion of it and "dead vs done"](https://news.ycombinator.com/item?id=24478236).

/cc @sayrer @fat @mattrobenolt

**Comment by gasche** [comment]
The project appears unmaintained, see #248. The last change was merged by @alanbato, who may be able to confirm. (Ideally it would be nice to clarify this on the project webpage.)

**Comment by willnorris** [comment]
Assigning to myself to track this down and try to get some kind of resolution.

**Comment by nfantone** [comment]
@willnorris  Any updates here? We are deciding whether to migrate away from Hogan on an old service that we have. Would be nice to have some input.

**Comment by sayrer** [comment]
Going to close this in favor of #272.
