### ISSUE TITLE
[Feature request] Registering partials

### ISSUE THREAD

**Issue by kapowaz** [twitter/hogan.js#38]
The current implementation of template.render() assumes that you know exactly what partials (if any) a given template references, which makes calling this method elsewhere somewhat problematic — you need to supply the partial as an argument to the call, which makes dynamically assembling calls to render a bit tricky.

Perhaps I'm missing some crucial detail of how partials are implemented, but if not I'd like to request a feature: that partials can be registered elsewhere (as Handlebars does) and then whenever a template is called it uses a previously registered partial of the appropriate name as it needs to.

**Comment by atk** [comment]
Currently I use an additional step between compilation and rendering to gather all of the required partials; however I find this most unsatisfying there is no builtin solution to that problem.
