### ISSUE TITLE
Lambda functions not supported in precompiled templates

### ISSUE THREAD

**Issue by arendjr** [twitter/hogan.js#75]
Hey guys,

I noticed lambda functions are not supported in precompiled templates. The core reason for this appears to be that the official Mustache specification reads:

> Lambdas are a special-cased data type for use in interpolations and sections.
> 
> (...)
> 
> When used as the data value for a Section tag, the lambda MUST be treatable as an arity 1 function, and invoked as such
> (passing a String containing the unprocessed section contents). The returned value MUST be rendered against the current
> delimiters, then interpolated in place of the section.

Unfortunately, this behavior requires that when a lambda function is used, the original (unprocessed) source of the template is available. In order to remedy this situation, I created a fork that works on the **processed** section contents instead (I've not created a pull request as it deliberately diverts from the spec to create the desired result).

Anyway, I think it's good to make you aware of this fork, and I'm looking for any feedback you guys can give me. Also, if you prefer I create a pull request for this, I can do that too.

One more question, I tried running the test suite through run.js to see if my changes had any unintended side-effects, but run.js gave me no output whatsoever. Probably I'm just unaware how to properly run the suite, but I didn't see instructions either, so if someone can point me to how to properly run the test suite that would be great.

You can find my fork right here: https://github.com/arendjr/hogan.js

Regards,
Arend jr.

**Comment by MeTaNoV** [comment]
I have the same issue with a similar use-case with Date... no news?

**Comment by prashaantt** [comment]
@MeTaNoV Please see the [discussion](https://github.com/twitter/hogan.js/issues/199) on the other thread I'd started. In particular, see the [tests](https://github.com/prashaantt/hogan.js/blob/master/test/index.js#L568-L585) to figure how Hogan is now handling lambdas: I could get it to work following the tests. It's a pity it's not documented, but I'm not even sure Hogan is being actively maintained anymore.

**Comment by MeTaNoV** [comment]
Thx @prashaantt !!! I get it to work also now... Well, like you, I was following the Mustache way, and am wondering now which one is correct, the current implementation of Hogan or Mustache...
